spring:
  application:
    name: bookMS
  datasource:
    driver-class-name : org.h2.Driver
    url : jdbc:h2:~/books
    username: admin
    password : 1234

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


# 로깅 설정
logging:
  level:
    root: INFO
    com.example.bookMS: DEBUG
    com.example.bookMS.aspect: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8

app.version: ${version}